name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14

      - name: Install dependencies
        run: npm install

      - name: Code Linting
        run: npm run lint

  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run jest:ci

  e2e_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14

      - name: Install Dependencies
        run: npm install

      - name: Run E2E Tests
        run: npm run start:ci
        